name: ShakerCI
description: Detect flaky tests in your repo in CI
branding: 
  icon: box
  color: yellow

inputs:
  tool:
    description: Tool
    required: true
  tests_command:
    description: Runner
    required: true
  output_folder:
    description: Folder
    required: true
  extra_arguments:
    description: Extra arguments
    required: false
  no_stress_runs:
    description: Number of no-stress runs
    default: "0"
    required: false
  runs:
    description: Number of Shaker runs
    default: "3"
    required: false

runs:
  using: docker
  image: Dockerfile
