name: Shaker
description: Runs Shaker in your repository

inputs:
  testing_tool:
    description: Testing tool
    required: true
  extra_arguments:
    description: Extra arguments
    required: false
  no_stress_runs:
    description: Number of no-stress runs
    default: "1"
    required: false
  stress_runs:
    description: Number of stress runs
    default: "3"
    required: false

runs:
  using: docker
  image: Dockerfile
